<?php return [
  'Add event' => 'Добавить событие',
  'Add header' => 'Добавить заголовок',
  'Cancel' => 'Отмена',
  'Close' => 'Закрыть',
  'Create webhook' => 'Создать вебхук',
  'Custom headers' => 'Пользовательские заголовки',
  'Delete' => 'Удалить',
  'Edit' => 'Редактировать',
  'Edit webhook' => 'Редактировать вебхук',
  'Events' => 'События',
  'HTTP body' => 'Тело HTTP-запроса',
  'HTTP settings' => 'HTTP-настройки',
  'Name' => 'Название',
  'No custom headers defined' => 'Нет пользовательских заголовков',
  'No events defined' => 'Нет событий',
  'No webhooks' => 'Нет вебхуков',
  'Payload' => 'Данные (Payload)',
  'Request Method' => 'Метод запроса',
  'Settings' => 'Настройки',
  'Trigger webhook' => 'Вызвать вебхук',
  'Update webhook' => 'Обновить вебхук',
  'Url' => 'URL',
  'Webhook created!' => 'Вебхук создан!',
  'Webhook triggered!' => 'Вебхук вызван!',
  'Webhook updated!' => 'Вебхук обновлён!',
  'Webhooks' => 'Вебхуки',
];